apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc2
  namespace: monitoring 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-grafana
