apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv2
spec:
  capacity:
    storage: 5Gi  # 명시적으로 용량을 설정
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-grafana
  nfs:
    path: /mnt/nfs/grafana  # NFS 서버의 공유 디렉토리 경로
    server: 10.10.1.1  # NFS 서버의 주소

