apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-jenkins
  nfs:
    path: /mnt/nfs/jenkins  # NFS 서버의 공유 디렉토리 경로
    server: 10.10.1.1  # NFS 서버의 주소

