apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/1ocate/local-k8s-manifests
    targetRevision: main
    path: argocd/applications  # ArgoCD에서 관리할 Application 목록
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
