apiVersion: v2
name: kube-prometheus-stack
description: A Helm chart for kube-prometheus-stack

type: application

version: 0.1.0

appVersion: "0.1.0"

dependencies:
- name: kube-prometheus-stack
  version: 70.4.1
  repository: https://prometheus-community.github.io/helm-charts
