apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-db-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany  # 여러 노드에서 읽기/쓰기가 가능하도록 설정
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-zabbix-db
