apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot-deploy
  namespace: telegram-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      containers:
      - name: telegram-bot
        image: python:3
        command: ["sh", "-c"]
        args: [
          "apt-get update && apt-get install -y iputils-ping && \
          pip install -r /usr/src/app/requirements.txt && \
          python /usr/src/app/telegram-bot.py"
        ]
        volumeMounts:
        - name: telegram-bot-volume
          mountPath: /usr/src/app
      volumes:
      - name: telegram-bot-volume
        persistentVolumeClaim:
          claimName: telegram-bot-pvc
