apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telegram-bot-pvc
  namespace: telegram
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: nfs-telegram-bot
