apiVersion: v2
name: ingress-nginx
description: A Helm chart for Ingress Nginx

type: application

version: 0.1.0

appVersion: "0.1.0"

dependencies:
- name: ingress-nginx
  version: 4.12.1
  repository: https://kubernetes.github.io/ingress-nginx
