apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-alertmanager-pv
spec:
  capacity:
    storage: 1Gi  # 명시적으로 용량을 설정
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    path: /mnt/nfs/kube-prometheus-stack/nfs-alertmanager  # NFS 서버의 공유 디렉토리 경로
    server: 10.10.1.1  # NFS 서버의 주소
