loki-stack:
  loki:
    enabled: true
    image:
      tag: '2.9.3'
    persistence:
      enabled: true
      size: 5Gi
      storageClassName: nfs-loki
      accessModes:
      - ReadWriteOnce
    config:
      limits_config:
        retention_period: 360h
        volume_enabled: true

      table_manager:
        retention_deletes_enabled: true
        retention_period: 360h

  promtail:
    enabled: true
    config:
      clients:
        - url: http://loki-stack.logging.svc.cluster.local:3100/loki/api/v1/push
  grafana:
    enabled: false

