apiVersion: v1
kind: PersistentVolume
metadata:
  name: telegram-bot-pv 
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-telegram-bot
  nfs:
    path: /mnt/nfs/telegram-bot  # NFS 서버의 공유 디렉토리 경로
    server: 10.10.1.1  # NFS 서버의 주소

